# Usar a imagem base do Nginx
FROM nginx:alpine

# Copiar o conteúdo do diretório local para o diretório /usr/share/nginx/html no contêiner
COPY . /usr/share/nginx/html

# Expor a porta 80 para o Nginx
EXPOSE 80
